import boy1 from '../assets/boy (1).jpg'
import boy2 from '../assets/boy (2).jpg'
import boy3 from '../assets/boy (3).jpg'
import boy4 from '../assets/boy (4).jpg'
import boy5 from '../assets/boy (5).jpg'
import boy6 from '../assets/boy (6).jpg'
import boy7 from '../assets/boy (7).jpg'
import boy8 from '../assets/boy (8).jpg'
import boy9 from '../assets/boy (9).jpg'
import boy10 from '../assets/boy (10).jpg'
import building1 from '../assets/building (1).jpg'
import building2 from '../assets/building (2).jpg'
import building3 from '../assets/building (3).jpg'
import building4 from '../assets/building (4).jpg'
import building5 from '../assets/building (5).jpg'
import building6 from '../assets/building (6).jpg'
import building7 from '../assets/building (7).jpg'
import building8 from '../assets/building (8).jpg'
import building9 from '../assets/building (9).jpg'
import building10 from '../assets/building (10).jpg'
import forest1 from '../assets/forest (1).jpg'
import forest2 from '../assets/forest (2).jpg'
import forest3 from '../assets/forest (3).jpg'
import forest4 from '../assets/forest (4).jpg'
import forest5 from '../assets/forest (5).jpg'
import forest6 from '../assets/forest (6).jpg'
import forest7 from '../assets/forest (7).jpg'
import forest8 from '../assets/forest (8).jpg'
import forest9 from '../assets/forest (9).jpg'
import forest10 from '../assets/forest (10).jpg'
import girl1 from '../assets/girl (1).jpg'
import girl2 from '../assets/girl (2).jpg'
import girl3 from '../assets/girl (3).jpg'
import girl4 from '../assets/girl (4).jpg'
import girl5 from '../assets/girl (5).jpg'
import girl6 from '../assets/girl (6).jpg'
import girl7 from '../assets/girl (7).jpg'
import girl8 from '../assets/girl (8).jpg'
import girl9 from '../assets/girl (9).jpg'
import girl10 from '../assets/girl (10).jpg'
import house1 from '../assets/house (1).jpg'
import house2 from '../assets/house (2).jpg'
import house3 from '../assets/house (3).jpg'
import house4 from '../assets/house (4).jpg'
import house5 from '../assets/house (5).jpg'
import house6 from '../assets/house (6).jpg'
import house7 from '../assets/house (7).jpg'
import house8 from '../assets/house (8).jpg'
import house9 from '../assets/house (9).jpg'
import house10 from '../assets/house (10).jpg'

export {
    boy1, boy2, boy3, boy4, boy5, boy6, boy7, boy8, boy9, boy10,
    building1, building2, building3, building4, building5, building6, building7, building8, building9, building10,
    forest1, forest2, forest3, forest4, forest5, forest6, forest7, forest8, forest9, forest10,
    girl1, girl2, girl3, girl4, girl5, girl6, girl7, girl8, girl9, girl10,
    house1, house2, house3, house4, house5, house6, house7, house8, house9, house10
}